### ISSUE TITLE
Bug: Only first row moving when dragging table

### ISSUE THREAD

**Issue by aikozim** [NiclasDev63/tiptap-extension-global-drag-handle#13]
Hi there!
I'm having trouble dragging tables using the drag handle, similar to issue #5. Here's my current configuration:
```
CopyGlobalDragHandle.configure({
  dragHandleWidth: 20,
}),
Table.configure({
  cellMinWidth: 0,
  allowTableNodeSelection: true,
})
```
Adding `allowTableNodeSelection: true` didn't solve the problem. It seems the drag handle isn't selecting the whole table. I've tried various solutions without success.
Any suggestions on how to fix this? I've attached a video demonstrating the issue.
Thanks for your help!

https://github.com/NiclasDev63/tiptap-extension-global-drag-handle/assets/47828495/3f59bd72-50d7-4017-89a8-b5d4093fbc43

**Comment by NiclasDev63** [comment]
Just fixed the problem and updated the package

**Comment by aikozim** [comment]
Thank you Niclas for the quick fix! The issue is now resolved. It's wonderful to see such responsive support in the community.

For future reference, to anyone encountering similar issues:
Please ensure that you have set the `allowTableNodeSelection: true` flag in your configuration.
