### ISSUE TITLE
Not working well with the Mentions extensions

### ISSUE THREAD

**Issue by jacquesg** [NiclasDev63/tiptap-extension-global-drag-handle#15]
Thank you for an awesome plugin, this is exactly what I needed. There is a weird interaction with the Mention plugin:

While dragging, it correctly shows that it will drag the block, as soon as I drop it, it only takes the actual mention element, and leaves the remaining text in the original position.

What I'm seeing is below:

<img width="514" alt="image" src="https://github.com/user-attachments/assets/bf0c0031-459d-4c6e-8496-5cd6c4ebed14">

<img width="533" alt="image" src="https://github.com/user-attachments/assets/e14fc3a9-a872-4f57-8d82-7111154b7090">

<img width="527" alt="image" src="https://github.com/user-attachments/assets/f2dc008c-3f78-438e-989d-2c5157aaedab">

**Comment by NiclasDev63** [comment]
I just tested it and it seems to work. Can you provide the code to reproduce your behaviour?

**Comment by jacquesg** [comment]
Hi,

Well, its pretty standard stuff, the only thing that may be different could be the way we set up the Mentions plugin:

```typescript
          Mention.extend({
            name: 'substitution',
          }).configure({
            HTMLAttributes: {
              class: 'mention',
            },
            suggestion: makeSuggestionOptions(makeSubstitutions(substitutions)),
            renderHTML({ node }) {
              return ['span', { class: 'mention' }, `${node.attrs.label ?? node.attrs.id}`];
            },
            renderText({ node }) {
              return `${node.attrs.label ?? node.attrs.id}`;
            },
          })

```

**Comment by jacquesg** [comment]
Also of interest maybe would be that the following node, when dragged, "drags" only the mention item, not the block:

```json
    {
      "type": "paragraph",
      "attrs": {
        "textAlign": "left"
      },
      "content": [
        {
          "type": "text",
          "text": "My "
        },
        {
          "type": "substitution",
          "attrs": {
            "id": "country",
            "label": "country"
          }
        },
        {
          "type": "text",
          "text": " "
        }
      ]
    },
```

**Comment by NiclasDev63** [comment]
The newest commit should fix this issue

**Comment by jacquesg** [comment]
@NiclasDev63 Just tested it out, fixes it for me, thank you!
