### ISSUE TITLE
Can't get it to work

### ISSUE THREAD

**Issue by nachodeh** [NiclasDev63/tiptap-extension-global-drag-handle#16]
Followed the instructions but can't get this to work.

Tried the setup verbatim and can't see any drag handles
Added some custom styling and a custom class and can't see drag handles

Can you provide a working example?

**Comment by NiclasDev63** [comment]
normally you should be able to simply add the plugin to your editor and then use something like the following css https://github.com/NiclasDev63/tiptap-extension-global-drag-handle/issues/9.
Can you provide the code to reproduce your behaviour ?

**Comment by nachodeh** [comment]
@NiclasDev63 my bad, there was an issue with my css styling and given I was testing with the inspector open, I never got it to show on hover. Works like a charm with this css and the simple setup from the homepage. Thanks!
