### ISSUE TITLE
Prevent drop based on condition

### ISSUE THREAD

**Issue by bernaferrari** [NiclasDev63/tiptap-extension-global-drag-handle#27]
I have something like:

- a table with text inside
- another table
 
I want to be able to reorder this table, but I don't want to be able to drop inside another table. Is there a way to prevent some movements, but allow others?

**Comment by NiclasDev63** [comment]
You should do this in the table schema definition. It is has nothing to do with the drag handle. See https://tiptap.dev/docs/editor/core-concepts/schema#the-node-schema for more information.

**Comment by bernaferrari** [comment]
Interesting. I was thinking because drag handle is the only source of entry, but that also makes sense. Thanks!
