### ISSUE TITLE
drag handle bounces when hovering over list items

### ISSUE THREAD

**Issue by andrewdoro** [NiclasDev63/tiptap-extension-global-drag-handle#3]
When moving over lists, drag handle bounces when hovering over empty space between list items. 

https://github.com/NiclasDev63/tiptap-extension-global-drag-handle/assets/17547035/4f4591f6-ad84-4fc6-8a27-755f43eceba7

I think we should add back this change. @NiclasDev63 would this break something?
https://github.com/steven-tey/novel/pull/350/files#diff-3ec542dadc4d00f74660b7d7b8bb35bfcf9caf6d8b2ebf322fdf0cc7a5ccbdf6R168

**Comment by NiclasDev63** [comment]
Just fixed this issue and published a new version of the package

**Comment by andrewdoro** [comment]
@NiclasDev63 I think you forgot to run npm run build before publish, I don't see the changes there

**Comment by NiclasDev63** [comment]
🤦‍♂️ you're right, everything should work now

**Comment by andrewdoro** [comment]
working now, thanks
